name: Ubuntu Engine

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  booting:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Setting Up User
      run: bash user.sh

    - name: Update and Upgrade Packages
      run: bash update.sh

    #- name: Installing Desktop GNOME
      #run: bash desktop.sh

    #- name: Installing XRDP
      #run: bash xrdp.sh

    - name: Configuring Ngrok
      run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar -xvf ngrok-v3-stable-linux-amd64.tgz
          ./ngrok authtoken 2jjqJ8mTlps4zo2wDNnREY5Xups_5BJT4C1zFSDQcyGQYqg1b
          ./ngrok tcp 22 &

    - name: Holder
      run: sleep 86400  # 24 hours in seconds
