name: Core Stack

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  booting:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Update and Upgrade Packages
      run: bash update.sh
