name: Core Stack

on:
  repository_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Update and Upgrade Packages
      run: bash update.sh
