name: Core Stack

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  booting:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Setting Up User
      run: bash user.sh

    - name: Update and Upgrade Packages
      run: bash update.sh

    - name: Installing Desktop GNOME
      run: bash desktop.sh

    - name: Installing XRDP
      run: bash xrdp.sh

    - name: Installing Ngrok
      run: bash ngrok.sh

    - name: Holder
      run: sleep 86400  # 24 hours in seconds
